services:
  - type: web
    name: kozmicke-bane
    runtime: python
    buildCommand: pip install -r requirements_cloud.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
    disk:
      name: gamedata
      mountPath: /opt/render/project/src
      sizeGB: 1
